jdac:
  baseUrl: http://localhost:8080/service/default
  basePackage: net.backlogic.persistence.springboot.classic
  logRequest: false
  jwtProvider:
    class: net.backlogic.persistence.client.auth.SimpleJwtProvider
    jwt: " "
